source/Meadow.Core/Gateways/Bluetooth/Definitions/CharacteristicBool.cs, source/Meadow.Core/Gateways/Bluetooth/Definitions/CharacteristicInt32.cs, source/Meadow.Core/Gateways/Bluetooth/Definitions/CharacteristicString.cs, source/Meadow.Core/Hardware/Communications/SerialMessagePort.cs, source/Meadow.Core/Hardware/Communications/SerialPortBase.cs, source/Meadow.Core/Hardware/DigitalInputPort.cs, source/Meadow.Core/MeadowOS.cs, source/Meadow.Core/MeadowSynchronizationContext.cs, source/Meadow.Core/Utilities/Output.cs, source/Meadow.F7/Devices/F7GPIOManager.cs, source/Meadow.F7/Devices/F7GPIOManager_interrupts.cs, source/Meadow.F7/F7PlatformOS.Configuration.cs, source/Meadow.F7/Hardware/Communications/F7SerialPort.cs, source/Meadow.F7/Hardware/Communications/I2cBus.cs, source/Meadow.F7/Interop/Interop.upd.cs, source/Meadow.F7/UPD.cs, source/Tests/Core.Unit.Tests/CircularBuffer_ExtensionMethod_Tests.cs
Updated most of the `Console.Write*` usage to whatever `Resolver.Log.*` call seemed appropriate.
I didn't update the uses in [ProfilerApp.cs](https://github.com/WildernessLabs/Meadow.Core/blob/develop/source/Tests/Profiler/ProfilerApp.cs) because I hadn't tested if this would have any performance impact, but it shouldn't be hard to do, if desired.
=> Switch to logger usage

README.md
Not sure we want to use `develop` here, but `main` is currently failing anyway.
=> Limit build badge to develop

source/Meadow.Core/Configuration/AppSettings.cs, source/Meadow.Core/Configuration/AppSettingsParser.cs, source/Meadow.Core/Configuration/MeadowAppSettings.cs, source/Meadow.Core/Configuration/MeadowCloudSettings.cs, source/Meadow.Core/Configuration/MeadowUpdateSettings.cs, source/Meadow.Core/MeadowCloudService.cs, source/Meadow.Core/MeadowOS.cs, source/Meadow.Core/Update/UpdateService.cs, source/Tests/Core.Unit.Tests/AppConfigParserTests.cs
* Create `MeadowCloudService` for Meadow.Cloud related interactions. Also, refactored `Authenticate()` into this service.
* Create `SendLog()` method to push log to Meadow.Cloud
* Create `MeadowCloudSettings`
Local testing: I sent a log every minute successfully for over two hours, re-authenticating twice after a 401. The auth tokens from the server expire after one hour, so this is expected.
=> Logging to Meadow.Cloud

source/Meadow.Core/Configuration/MeadowUpdateSettings.cs, source/Meadow.Core/Update/UpdateService.cs
This adds an additional MQTT topic that a device subscribes to that includes the organization id. That organization id is retrieved from the device's JWT.
=> Update RootTopic to support organization id for OtA updates

source/Meadow.Core/Configuration/MeadowUpdateSettings.cs
This updates the default MQTT settings used for OtA updates for use with the new MQTT server.
=> Update default MQTT settings for OtA updates

source/Meadow.Core/Configuration/MeadowCloudSettings.cs
update DataHostname for CloudLogger to proper prod uri
=> set default DataHostname for production

.github/workflows/ci-build.yml, source/Meadow.Core/Configuration/MeadowUpdateSettings.cs, source/Meadow.Core/MeadowOS.cs, source/Meadow.Core/Update/UpdateService.cs, source/Tests/Core.Unit.Tests/Core.Unit.Tests.csproj, source/Tests/Core.Unit.Tests/UpdateServiceTests/CommandServiceTests.cs, source/Tests/Core.Unit.Tests/UpdateServiceTests/ProcessPublishedCommandTests.cs
This adds the implementation for the command and control feature of Meadow.Cloud. The interface and class contracts are a part of a [separate pull request in Meadow.Contracts](https://github.com/WildernessLabs/Meadow.Contracts/pull/128). The purpose of this feature is to allow a user to publish command messages to their Meadow devices and have their devices respond accordingly.
=> Add support for subscribing to Meadow.Cloud commands

source/Meadow.Core/HealthReporter.cs, source/implementations/f7/Meadow.F7/Devices/F7CoreComputeBase.cs, source/implementations/f7/Meadow.F7/Devices/F7FeatherV1.cs, source/implementations/f7/Meadow.F7/Devices/F7FeatherV2.cs, source/implementations/f7/Meadow.F7/Devices/F7MicroBase.cs
* start health reporter timer after network is connected.
* only send battery info if it's available on the device
* send `null` `BatteryInfo` for CCM device
=> health reporter improvements and CCM batteryinfo fix

source/Meadow.Core/MeadowOS.cs
Only return false on the catch block is not a good practice, the exception may not just be the
$"Failed to create instance of '{deviceType.Name}'", and if so, the user will have a hard time to figure out which is the real issue.
I caught this because I was trying to use the lib into a container and it was not binding the `/var/lib/dbus/machine-id`. So, I had to go to the lib source code and debug it ...
=> MeadowOS: Add trace to catch block exception on device creation

source/Meadow.Core/Configuration/MeadowUpdateSettings.cs, source/Meadow.Core/Update/UpdateService.cs
This updates the MQTT settings for the UpdateService and CommandService for OtA and Command/Control, respectively, to use TLS by default.
=> Update MQTT settings to TLS by default

source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/Esp32WiFiAdapter.cs
I created an app to test the WiFi connection, but when F7 disconnected to the Access Point the variable Is Connected still was true even after receiving the NetworkDisconnected event.
```
Meadow StdOut: Try connecting ...
Meadow StdOut: Try connecting ...
Meadow StdOut: Connected :) | 0
Meadow StdOut: Connected :) | 1
Meadow StdOut: WiFi connected.
Meadow StdOut: Connected :) | 2
Meadow StdOut: Connected :) | 3
Meadow StdOut: Connected :) | 4
...
Meadow StdOut: Connected :) | 20
Meadow StdOut: WiFi disconnected.
Meadow StdOut: Connected :) | 0
Meadow StdOut: Connected :) | 1
Meadow StdOut: Connected :) | 2
Meadow StdOut: Connected :) | 3
Meadow StdOut: Connected :) | 4
...
```
=> Fix disconnect wifi

source/implementations/f7/Meadow.F7/F7PlatformOS.cs, source/implementations/f7/Meadow.F7/Interop/Interop.cs, source/implementations/f7/Meadow.F7/Interop/Interop.mbedtls.cs, source/implementations/linux/Meadow.Linux/PlatformOS/LinuxPlatformOS.cs, source/implementations/simulation/Meadow.Simulation/SimulatedPlatformOS.cs, source/implementations/windows/Meadow.Windows/WindowsPlatformOS.cs
- https://github.com/WildernessLabs/Meadow_Issues/issues/377
- https://github.com/WildernessLabs/Meadow.Contracts/pull/159
- https://github.com/WildernessLabs/Meadow/pull/499
=> Make server certificate validation optional

source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/Esp32WiFiAdapter.cs
The aim is to update network status when the Default Connection proceeds starting, this way,  avoid taking a long time waiting for Auto-Connect to complete when the `Connect` method is called.
Respective issue :
- https://github.com/WildernessLabs/Meadow_Issues/issues/396
=> Updating Network Status when the Default Connection started.

source/implementations/f7/Meadow.F7/Devices/F7CellNetworkAdapter.cs, source/implementations/f7/Meadow.F7/Interop/Interop.cell.cs
- https://github.com/WildernessLabs/Meadow.Contracts/pull/203
**Summary**
- Adjust cell error messages
- Change `Csq` property, and `GetSignalQuality` types to `int`
- Retrieve signal quality in `dBm`
- Deprecate the old network scanner method (`OfflineNetworkScan`)
- Remove underscore from network mode types, to keep consistency with the OS side.
=> Adjust cell error messages, and cell signal quality return type

source/Meadow.Core/NetworkAdapterBase.cs, source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/Esp32WiFiAdapter.cs
The aim of this PR is to refresh the network info after disconnecting from the AP and solving the issue below:
- https://github.com/WildernessLabs/Meadow_Issues/issues/290
=> Update the Networking Interface Info

source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/SharedEnums.cs
Added some OS status codes and synchronised the values in the enum.
This is preparation work for getting the ESP reset reasons from the OS to Core.
=> Added some missing status codes.

source/Meadow.Core/Cloud/MeadowCloudConnectionService.cs
Since TLS handshake additional error messages are nested as inner exceptions, they must be handled accordingly.
=> Handle TLS inner exceptions

source/Meadow.Core/Cloud/MeadowCloudConnectionService.cs
**Summary**
When the `Authenticate()` fails in the `Send<T>` task, Meadow.Core attempts to make requests with an empty `_jwt`, which will always fail, and retrieve `InternalServerError` from the server. So, this PR aims to retry the authentication when it fails.
=> Fix empty bearer requests issue

source/Meadow.Core/Cloud/MeadowCloudConnectionService.cs
[I have accidentally removed a condition that avoids reauthentication](https://github.com/WildernessLabs/Meadow.Core/commit/19b0510ff374933ac4b3641f7b29a3ec39a7de45) for every request, this PR aims to fix it.
=> Avoid reauthentication for each log sent

source/Meadow.Core/Configuration/AppSettingsParser.cs, source/Tests/Core.Unit.Tests/AppConfigParserTests.cs, source/Tests/Core.Unit.Tests/Core.Unit.Tests.csproj, source/Tests/Core.Unit.Tests/app.config.customsettings.yaml, source/Tests/Core.Unit.Tests/app.config.customsettingsafterempty.yaml
Following [this suggestion](https://github.com/WildernessLabs/Meadow_Issues/issues/718#issuecomment-2168057251), I started reading my custom settings directly from `IApp.Settings`. But I noticed that the keys for my settings weren't as expected. 
With the following configuration:
```yaml
MeadowCloud:
Enabled: false
MyApp:
Setting1: test1
Setting2: test2
```
My custom settings keys were prefixed with `MyApp` (e.g., `MyApp.Setting1`). However, if I comment out all the settings in the previous section:
```yaml
MeadowCloud:
MyApp:
Setting1: test1
Setting2: test2
```
My custom settings keys were now prefixed with `MeadowCloud.MyApp`, and my code to retrieve them failed with a `KeyNotFoundException`. 
The changes in this PR reset the settings level breadcrumbs when a new section starts, …
=> Ensure cleared path when starting new settings group

Source/implementations/f7/Meadow.F7/Devices/F7CoreComputeBase.cs
- https://github.com/WildernessLabs/Meadow_Issues/issues/725
This PR aims to remove a duplicated ethernet adapter:
```
Meadow StdOut: adapter: Meadow.Devices.WiredNetworkAdapter
Meadow StdOut: adapter: Meadow.Devices.F7EthernetNetworkAdapter
```
It explains why the subscribed methods are not being called when the NetworkConnected event is triggered. Basically, when the user does:
`var ethernet = Device.NetworkAdapters.Primary<IWiredNetworkAdapter>();`
It retrieves one of the adapters, which is not necessarily the one used for handling events.
=> Remove duplicate ethernet adapter

Source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/SharedEnums.cs, Source/implementations/f7/Meadow.F7/Devices/F7CellNetworkAdapter.cs
The PR aims to add two new events on the cell (Connecting and RetryExceeded).
Meadow PR :
-  https://github.com/WildernessLabs/Meadow/pull/627 
Issue :
- https://github.com/WildernessLabs/Meadow_Issues/issues/641
```
Cell InvokeEvent NetworkConnectingEvent returned CompletedOk
Cell connecting event triggered!
Cell network connecting!
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script failed, retrying...
Cell connect script …
```
=> improve connection eventing on cell

Source/Meadow.Core/Gateways/Bluetooth/Definitions/Definition.cs
Add a company UUID to be used to identify the device manufacturer.
=> Add the ability to set a company UUID.

Source/Meadow.Core/Gateways/Bluetooth/Definitions/Definition.cs
Allow the user to specify the company identifier assigned number for Bluetooth interface.
Resolves issue https://github.com/WildernessLabs/Meadow_Issues/issues/210
=> Allow the user to set the company assigned number.

Source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/SharedEnums.cs
Added some enums for consistency across the three platfoms.
Events will be raised in a future ESP PR.
=> Add enum definitions for Bluetooth events and updated some comments.

Source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/SharedEnums.cs
Trivial change to keep the shared enums in sync.
=> Synchronise shared enums across managed/stm/esp code bases.

Source/Meadow.Core/Cloud/MeadowCloudConnectionService.cs
Set `clean session` to `false` and configure a session `expiry interval` of 24 hours (3600 * 24 seconds). This ensures that MQTT commands sent while the device is offline will be delivered once it reconnects. ([#809](https://github.com/WildernessLabs/Meadow_Issues/issues/809))
=> Set persistent connections on MQTT client side

Source/Meadow.Core/Cloud/MeadowCloudUpdateService.cs
- Add more exception data to the OTA download error message
More context can be seen in the [private slack discussion](https://wildernesslabs.slack.com/archives/CFNK2MFTR/p1724806505576009).
=> Add more exception data to the OTA download error message

Source/implementations/f7/Meadow.F7/Devices/Esp32Coprocessor/Esp32Coprocessor.cs
Currently event data is displayed something like this:
```
[esp] Simple event, interface 2, event code: 5, status code 0x00000000
```
This PR makes the output more readable:
```
[esp] Simple event, interface BlueTooth, event code: BluetoothStartingEvent, status code CompletedOk (0x00000000)
```
=> Make the event data more readable.
